// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz_Xb6xLwr3ZOzDI3ZtDJAYKNVpCi31GQ',
    appId: '1:539336309135:web:b6718c2b1635a6bcf3f3fa',
    messagingSenderId: '539336309135',
    projectId: 'xeneize-app',
    authDomain: 'xeneize-app.firebaseapp.com',
    storageBucket: 'xeneize-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvhflOx9rI7eDvXeQcyoG2qR0nW0qYvPQ',
    appId: '1:539336309135:android:92464a7a62c6c310f3f3fa',
    messagingSenderId: '539336309135',
    projectId: 'xeneize-app',
    storageBucket: 'xeneize-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFT4MdXdsARPcBZVaV1GO3awB4ZSK15A',
    appId: '1:539336309135:ios:4d5f77b6de27c3d4f3f3fa',
    messagingSenderId: '539336309135',
    projectId: 'xeneize-app',
    storageBucket: 'xeneize-app.firebasestorage.app',
    iosBundleId: 'com.example.xeneizeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGFT4MdXdsARPcBZVaV1GO3awB4ZSK15A',
    appId: '1:539336309135:ios:4d5f77b6de27c3d4f3f3fa',
    messagingSenderId: '539336309135',
    projectId: 'xeneize-app',
    storageBucket: 'xeneize-app.firebasestorage.app',
    iosBundleId: 'com.example.xeneizeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz_Xb6xLwr3ZOzDI3ZtDJAYKNVpCi31GQ',
    appId: '1:539336309135:web:af9e7b9dc0c6c650f3f3fa',
    messagingSenderId: '539336309135',
    projectId: 'xeneize-app',
    authDomain: 'xeneize-app.firebaseapp.com',
    storageBucket: 'xeneize-app.firebasestorage.app',
  );
}
